{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shot.fullname" . }}-api
  labels:
    {{- include "shot.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shot.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
{{- end }}
