{{- if .Values.storybook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qurvo.fullname" . }}-storybook-basic-auth
  labels:
    {{- include "qurvo.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.storybook.basicAuth.htpasswd | b64enc | quote }}
{{- end }}
