{{- if .Values.storybook.enabled }}
{{- if not .Values.storybook.basicAuth.htpasswd }}
{{- fail "storybook.basicAuth.htpasswd must be set in values.local-secrets.yaml (generate with: htpasswd -nb <user> <password>)" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qurvo.fullname" . }}-storybook-basic-auth
  labels:
    {{- include "qurvo.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.storybook.basicAuth.htpasswd | b64enc | quote }}
{{- end }}
