global:
  imageTag: "staging"

domain:
  app: "app.qurvo.ru"
  ingest: "ingest.qurvo.ru"

tls:
  clusterIssuer: "letsencrypt-staging"

api:
  replicas: 1
  env:
    CORS_ORIGIN: "https://app.qurvo.ru"

ingest:
  replicas: 1

processor:
  replicas: 1

web:
  replicas: 1
