apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qurvo.fullname" . }}-config
  labels:
    {{- include "qurvo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  NODE_ENV: "production"
  CLICKHOUSE_DB: {{ .Values.clickhouse.database | quote }}
