apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qurvo.fullname" . }}-config
  labels:
    {{- include "qurvo.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  CLICKHOUSE_DB: {{ .Values.clickhouse.database | quote }}
