{{- if .Values.ingest.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shot.fullname" . }}-ingest
  labels:
    {{- include "shot.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.clusterIssuer | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.domain.ingest }}
      secretName: {{ include "shot.fullname" . }}-ingest-tls
  {{- end }}
  rules:
    - host: {{ .Values.domain.ingest }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shot.fullname" . }}-ingest
                port:
                  name: http
{{- end }}
