apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shot.fullname" . }}-secret
  labels:
    {{- include "shot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ required "secrets.redisUrl is required" .Values.secrets.redisUrl | quote }}
  CLICKHOUSE_URL: {{ required "secrets.clickhouseUrl is required" .Values.secrets.clickhouseUrl | quote }}
  CLICKHOUSE_USER: {{ required "secrets.clickhouseUser is required" .Values.secrets.clickhouseUser | quote }}
  CLICKHOUSE_PASSWORD: {{ required "secrets.clickhousePassword is required" .Values.secrets.clickhousePassword | quote }}
