{{- if .Values.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qurvo.fullname" . }}-ingest
  labels:
    {{- include "qurvo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ingest.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qurvo.selectorLabels" (dict "component" "ingest" "root" .) | nindent 4 }}
{{- end }}
